server:
  port: 8000

#spring:
#  application:
#    name: cloud-order-service

eureka:
  client:
    register-with-eureka: false #是否注册进Eureka
#    fetch-registry: true #是否从EurekaServer抓取已有的注册信息，默认true，单节点无所谓，集群必须为true配合
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka, http://eureka7003.com:7003/eureka

#设置feign客户端超时时间(openFeign默认支持ribbon)
ribbon:
  #指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间
  ReadTimeout: 5000
  #指的是建立连接后从服务读取到可用资源所用的时间
  ConnectTimeout: 5000

logging:
  level:
    #feign日志以什么级别监控哪个接口
    com.cloud.iot.service.PaymentFeignService: debug

feign:
  hystrix:
    enabled: true #openFeign打开hystrix


