server:
  port: 7003

eureka:
  instance:
    hostname: eureka7003.com #服务端实例名称
  client:
    register-with-eureka: false #falst表示不向注册中心注册自己
    fetch-registry: false #false表示自己端就是注册中心，我的指责就是维护服务实例，并不需要检索服务
    service-url:
      #设置与Eureka server交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://eureka7002.com:7002/eureka/
      #单机版配置
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    #关闭自我保护机制
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 2000